version: 3
env:
  S3_BUCKET: decisionchat
tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
  install_dependencies:
    cmds:
      - cd python-lambda && pip3 install -r requirements.txt --target package

  upload_initial:
    env:
      FILENAME: initial.json
    cmds:
      - aws s3 cp $FILENAME s3://$S3_BUCKET/$FILENAME

  zip_python_lambda:
    cmds:
      - 

  update_python_lambda: